SQL MINDMAP:
===============

DATA : RAW DATA OR SOMNE INFORMATION.

INFORMATION : RELATED DATA OR MEANINGFUL DATA.

DATABASE  : COLLECTION OF RELATED DATA


OBJECTS : IT IS STRUCTURE IN WHICH USED TO STORE DATA IN DB.
LIST OF OBJECTS :                  
                    TABLE  :DATA STORED IN ROW AND COLUMN FORMAT.
                    VIEW   : LOGICALLY REPRESENT DATA ,ADDING 2 OR MORE TABLES.
                    INDEX  : USED TO IMPROVE PERFORMANCE OF QUERY.
                    CONSTRAINTS : USED TO RESTRICT DATA TO INFORCE RULES IN TABLE.
                    SYNONYM  : IT IS ALTERNATIVE NAME TO OBJECTS.
                    SEQUENCE : USED TO GENERATE PRIMARY KEY VALUES.
                    TRIGGERS : INVOKES AUTOMATICALLY WHENEVER SPECIFIED EVENT OCCURS.
======================================================
ADVANTAGES OF DBMS:
----------------------
                    RETRIEVING DATA ,
                    DATA SECURITY,
                    NO CHANCE OF DATA DUPLICACY,
                    INDEXING PROPERLY,
                    DATA INTEGRITY(RULES FOR SAVING DATA),ENSURING DATA IS ACCURATE CONSISTENT AND COMPLETE.
=======================================================
WHAT IS SQL ?
-------------
IT IS A QUERY LANGUAGE,
USED TO ACCESS AND MANIPULATE DATA,
PERFORMING CRUD OPERATIONS.

==============================================================
--SQL STATEMENTS 
-----------------------------------------
DDL : DATA DEFINATION LANGUAGE  
        USED TO DEAL WITH OBJECTS IN DB
    CREATE
    ALTER
    DROP
    TRUNCATE
    RENAME
    COMMENT
    
DML : DATA MANIPULATION LANGUAGE
        USED TO MODIFY DATA IN TABLE
    SELECT 
    INSERT
    UPDATE
    DELETE
    
    
DCL : DATA CONTROL LANGUAGE
     USED TO GIVE OR REMOVE PERMISSION FROM USER.
    GRANT
    REVOKE

TCL : TRANSACTION CONTROL LANGUAGE
    USED TO CONTROL TRANSACTION.    
    COMMIT
    ROLLBACK
    SAVEPOINT
    
