DDL STATEMENTS:
=================

DDL : DATA DEFINATION LANGUAGE  
        USED TO DEAL WITH OBJECTS IN DB
----------------------------------------------------------
    CREATE : USED TO CREATE OBJECTS IN DB.
    ALTER : USED TO MODIFY EXISTING OBJECTS IN DB.
    DROP  : USED TO REMOVE TABLE COMPLETELY WITH ITS STRUCTURE IN DB.
    TRUNCATE : USED TO DELETE DATA WITHOUT WITHOUT ITS STRUCTURE IN DB.
    RENAME   : USED TO RENAME COLUMN NAME AND TABLE NAME IN DB.
    COMMENT : USED TO ADD COMMENT IN TABLE OR DATABASE.
--WE WILL WORK ON OBJECTS STEP BY STEP:
-------------------------------------
TABLE : DATA STORED IN ROW AND COLUMN FORMAT.

--HOW TO CREATE TABLE ?
CREATE TABLE XXPT_EMP
AS SELECT * FROM EMP;

DESC XXPT_EMP;
--CREATE STATEMENT :
--HOW TO CREATE A TABLE ?

CREATE TABLE XXPT_EMP
(
EMPNO    NOT NULL NUMBER(4),    
ENAME             VARCHAR2(50), 
JOB               VARCHAR2(50), 
MGR               NUMBER(4),    
HIREDATE          DATE   ,      
SAL               NUMBER(7,2),  
COMM              NUMBER(7,2),  
DEPTNO            NUMBER(2)   
);                                 -- OUTPUT := TABLE XXPT_EMP CREATED.

--ALTER STATEMENT :                    
--HOW TO MODIFY TABLE ? 
--HOW TO ADD NEW COLUMN IN A TABLE ?
ALTER TABLE XXPT_EMP
ADD EMAIL VARCHAR2(50);            -- OUTPUT := EMAIL COLUMN ADDED.

--HOW TO REMOVE COLUMN IN A TABLE ?
ALTER TABLE XXPT_EMP
DROP COLUMN EMAIL ;                -- OUTPUT := EMAIL COLUMN DROPPED.

--HOW TO RENAME COLUMN NAME IN TABLE ?
ALTER TABLE XXPT_EMP
RENAME COLUMN ENAME TO EMP_NAME;   -- OUTPUT := RENAME COLUMN ENAME TO EMP_NAME

--HOW TO RENAME TABLE ?
RENAME XXPT_EMP TO XX_EMP;         -- OUTPUT := TABLE RENAMED XXPT_EMP TO XX_EMP

--HOW TO MODIFY DATATYPE OF A PARTICULAR COLUMN ?
ALTER TABLE XX_EMP
MODIFY  JOB VARCHAR2(100);          -- OUTPUT := TABLE COLUMN DATATYPE CHANGED TO VARCHAR2(100)


--DROP STATEMENT
--HOW TO DELETE TABLE IN DB?
DROP TABLE XXPT_EMP;                -- OUTPUT := TABLE DROPPED COMPLETELY


--TRUNCATE  STATEMENT :
--HOW TO DELETE ALL DATA FROM TABLE BUT REMANIN ITS STRUCTURE?
TRUNCATE TABLE XXPT_EMP;

