ALIASING IN ORACLE SQL : USED TO GIVE ALTERNATIVE NAME TEMPORARILY.
====================

COLUMN ALIAS : GIVE ALTERNATIVE NAME TO COLUMN
        SELECT SEGMENT1 PO_NUMBER FROM PO_HEADERS_ALL ;

TABLE ALIAS: GIVE ALTERNATIVE NAME TO TABLE 
			SELECT PHA.SEGMENT1 PO_NUMBER 
			FROM PO_HEADERS_ALL PHA;